using MagicaCloth2;
using System;
using System.Collections.Generic;
using UnityEngine;

namespace MagicaClothColliderBuilder
{
    public class ColliderGenerator
    {
        // Constants

        public const string GeneratedColliderName = "MagicaClothCollider";


        // Fields

        private readonly GameObject m_AvatarRoot;
        private readonly SABoneColliderProperty m_Property;
        private readonly Animator m_Animator;
        private readonly List<SkinnedMeshRenderer> m_CustomSkinnedMeshes;
        private readonly Action<float, string> m_ProgressReporter;

        private struct FitQualitySummary
        {
            public int Count;
            public float CoverageSum;
            public float MaxOverflowSum;
            public float WorstOverflow;

            public void Add(float coverage, float maxOverflow)
            {
                ++Count;
                CoverageSum += coverage;
                MaxOverflowSum += maxOverflow;
                WorstOverflow = Mathf.Max(WorstOverflow, maxOverflow);
            }
        }


        // Methods

        public ColliderGenerator(GameObject avatarRoot, SABoneColliderProperty properties, List<SkinnedMeshRenderer> customSkinnedMeshes = null, Action<float, string> progressReporter = null)
        {
            m_AvatarRoot = avatarRoot;
            m_Property = properties;
            m_Animator = avatarRoot.GetComponent<Animator>();
            m_CustomSkinnedMeshes = customSkinnedMeshes;
            m_ProgressReporter = progressReporter;
        }

        public List<MagicaCapsuleCollider> Process()
        {
            var createdColliders = new List<MagicaCapsuleCollider>();

            ReportProgress(0.02f, "Validating avatar settings...");

            if (m_Animator == null || m_Animator.avatar == null || !m_Animator.avatar.isHuman)
            {
                Debug.LogError("Animator with a valid Humanoid Avatar is required on the root object.");

                return createdColliders;
            }

            if (FindGeneratedColliders(m_AvatarRoot).Count > 0)
            {
                Debug.LogWarning("Generation skipped: existing colliders generated by this tool were found. Please cleanup first if you want to regenerate.");

                return createdColliders;
            }

            ReportProgress(0.10f, "Collecting humanoid bones...");

            var bonesToProcess = CollectHumanBones();

            if (bonesToProcess.Count == 0)
            {
                Debug.LogWarning("No human bones found to process.");

                return createdColliders;
            }

            ReportProgress(0.18f, "Building mesh cache...");

            var boneMeshCache = new BoneMeshCache();
            boneMeshCache.Process(m_AvatarRoot, m_CustomSkinnedMeshes);

            if (boneMeshCache.MeshBoneCount == 0)
            {
                Debug.LogError("No skinned meshes found to generate colliders from.");

                return createdColliders;
            }

            var generationJobs = new List<ColliderGenerationJob>();
            var bonesWithoutMesh = new List<Transform>();

            ReportProgress(0.24f, "Extracting per-bone meshes...");

            int boneCount = bonesToProcess.Count;

            for (int i = 0; i < boneCount; ++i)
            {
                var job = new ColliderGenerationJob(bonesToProcess[i].gameObject, m_Animator, m_Property, boneMeshCache);

                if (job.Prepare())
                {
                    generationJobs.Add(job);
                }
                else
                {
                    bonesWithoutMesh.Add(bonesToProcess[i]);
                }

                if (boneCount > 0 && ((i & 3) == 0 || i + 1 == boneCount))
                {
                    float t = (i + 1) / (float)boneCount;
                    string boneName = bonesToProcess[i] != null ? bonesToProcess[i].name : "Unknown";

                    ReportProgress(Mathf.Lerp(0.24f, 0.64f, t), $"Extracting mesh for {boneName} ({i + 1}/{boneCount})...");
                }
            }

            ReportProgress(0.66f, "Fitting collider shapes...");

            var qualitySummary = new FitQualitySummary();
            createdColliders.AddRange(CreateCollidersFromResults(generationJobs, ref qualitySummary));

            for (int i = 0; i < bonesWithoutMesh.Count; ++i)
            {
                var boneToFix = bonesWithoutMesh[i];
                ReportProgress(
                    Mathf.Lerp(0.90f, 0.98f, (i + 1) / (float)Mathf.Max(1, bonesWithoutMesh.Count)),
                    $"Creating fallback collider for {boneToFix.name} ({i + 1}/{bonesWithoutMesh.Count})...");

                var fallbackCollider = CreateDefaultColliderForBone(boneToFix);

                if (fallbackCollider != null)
                {
                    createdColliders.Add(fallbackCollider);
                }
            }

            Debug.Log($"Collider generation complete. Created {createdColliders.Count} colliders.");

            if (qualitySummary.Count > 0)
            {
                float averageCoverage = qualitySummary.CoverageSum / qualitySummary.Count;
                float averageMaxOverflow = qualitySummary.MaxOverflowSum / qualitySummary.Count;
                Debug.Log(
                    $"Collider fit quality: {qualitySummary.Count} fitted colliders, " +
                    $"average coverage {averageCoverage:P1}, " +
                    $"average max overflow {averageMaxOverflow:F4}m, " +
                    $"worst overflow {qualitySummary.WorstOverflow:F4}m.");
            }

            ReportProgress(1.0f, "Done.");

            return createdColliders;
        }

        public static List<MagicaCapsuleCollider> FindGeneratedColliders(GameObject avatarRoot)
        {
            var generatedColliders = new List<MagicaCapsuleCollider>();

            if (avatarRoot == null)
            {
                return generatedColliders;
            }

            var colliders = avatarRoot.GetComponentsInChildren<MagicaCapsuleCollider>(true);

            for (int i = 0; i < colliders.Length; ++i)
            {
                if (IsGeneratedCollider(colliders[i]))
                {
                    generatedColliders.Add(colliders[i]);
                }
            }

            return generatedColliders;
        }

        public static bool IsGeneratedCollider(MagicaCapsuleCollider collider)
        {
            return collider != null &&
                   collider.gameObject != null &&
                   collider.gameObject.name.StartsWith(GeneratedColliderName, StringComparison.Ordinal);
        }

        private void ReportProgress(float progress, string message)
        {
            m_ProgressReporter?.Invoke(Mathf.Clamp01(progress), message ?? string.Empty);
        }

        private List<Transform> CollectHumanBones()
        {
            var bones = new List<Transform>();
            var seen = new HashSet<Transform>();

            for (int i = 0; i < (int)HumanBodyBones.LastBone; i++)
            {
                HumanBodyBones boneId = (HumanBodyBones)i;

                if (!ShouldIncludeBone(boneId))
                {
                    continue;
                }

                var boneTransform = m_Animator.GetBoneTransform(boneId);

                if (boneTransform != null && seen.Add(boneTransform))
                {
                    bones.Add(boneTransform);
                }
            }

            return bones;
        }

        private bool ShouldIncludeBone(HumanBodyBones boneId)
        {
            if (IsFingerBone(boneId))
            {
                return m_Property.GenerationProperty.IncludeFingers;
            }

            if ((boneId == HumanBodyBones.LeftHand || boneId == HumanBodyBones.RightHand) &&
                m_Property.GenerationProperty.IncludeFingers)
            {
                return false;
            }

            if (boneId == HumanBodyBones.Hips)
            {
                return m_Property.GenerationProperty.IncludeHips;
            }

            if (boneId == HumanBodyBones.LeftShoulder || boneId == HumanBodyBones.RightShoulder)
            {
                return m_Property.GenerationProperty.IncludeShoulders;
            }

            if (boneId == HumanBodyBones.LeftToes || boneId == HumanBodyBones.RightToes)
            {
                return m_Property.GenerationProperty.IncludeToes;
            }

            if (boneId == HumanBodyBones.UpperChest)
            {
                return m_Property.GenerationProperty.IncludeUpperChest;
            }

            return boneId <= HumanBodyBones.RightToes;
        }

        private static bool IsFingerBone(HumanBodyBones boneId)
        {
            return boneId >= HumanBodyBones.LeftThumbProximal && boneId <= HumanBodyBones.RightLittleDistal;
        }

        private List<MagicaCapsuleCollider> CreateCollidersFromResults(List<ColliderGenerationJob> jobs, ref FitQualitySummary qualitySummary)
        {
            var createdColliders = new List<MagicaCapsuleCollider>();

            if (jobs == null || jobs.Count == 0)
            {
                return createdColliders;
            }

            for (int i = 0; i < jobs.Count; ++i)
            {
                var job = jobs[i];
                string boneName = job.TargetBone != null ? job.TargetBone.name : "Unknown";
                ReportProgress(Mathf.Lerp(0.66f, 0.88f, (i + 1) / (float)jobs.Count), $"Fitting {boneName} ({i + 1}/{jobs.Count})...");

                if (!ColliderCapsuleFitter.TryFitCapsule(job, out var fitResult)) continue;

                if (TryEvaluateFitQuality(job, fitResult, out float coverage, out float maxOverflow))
                {
                    qualitySummary.Add(coverage, maxOverflow);

                    if (coverage < 0.92f || maxOverflow > 0.025f)
                    {
                        Debug.LogWarning(
                            $"Collider fit for '{boneName}' may need review. " +
                            $"Coverage: {coverage:P1}, max overflow: {maxOverflow:F4}m.");
                    }
                }

                var collider = CreateColliderGameObject(job, fitResult);

                if (collider != null)
                {
                    createdColliders.Add(collider);
                }
            }

            return createdColliders;
        }

        private static bool TryEvaluateFitQuality(ColliderGenerationJob job, CapsuleFitResult fitResult, out float coverage, out float maxOverflow)
        {
            coverage = 0.0f;
            maxOverflow = 0.0f;

            var vertices = job.Vertices;

            if (vertices == null || vertices.Length == 0)
            {
                return false;
            }

            Quaternion inverseRotation = Quaternion.Inverse(fitResult.LocalRotation);
            float halfLength = Mathf.Max(0.0f, fitResult.Length * 0.5f);
            float minY = fitResult.Center.y - halfLength;
            float maxY = fitResult.Center.y + halfLength;
            int insideCount = 0;

            for (int i = 0; i < vertices.Length; ++i)
            {
                Vector3 local = inverseRotation * vertices[i];
                float clampedY = Mathf.Clamp(local.y, minY, maxY);
                float t = Mathf.InverseLerp(minY, maxY, clampedY);
                float allowedRadius = Mathf.Lerp(fitResult.RadiusAtMin, fitResult.RadiusAtMax, t);
                float dx = local.x - fitResult.Center.x;
                float dz = local.z - fitResult.Center.z;
                float radialOverflow = Mathf.Max(0.0f, Mathf.Sqrt((dx * dx) + (dz * dz)) - allowedRadius);
                float axialOverflow = Mathf.Abs(local.y - clampedY);
                float overflow = Mathf.Sqrt((radialOverflow * radialOverflow) + (axialOverflow * axialOverflow));

                if (overflow <= 0.001f)
                {
                    ++insideCount;
                }

                if (overflow > maxOverflow)
                {
                    maxOverflow = overflow;
                }
            }

            coverage = insideCount / (float)vertices.Length;
            return true;
        }

        private static MagicaCapsuleCollider CreateColliderGameObject(ColliderGenerationJob job, CapsuleFitResult fitResult)
        {
            var colliderGameObject = new GameObject(GeneratedColliderName);
            colliderGameObject.transform.parent = job.TargetBone.transform;
            colliderGameObject.transform.localPosition = Vector3.zero;
            colliderGameObject.transform.localRotation = fitResult.LocalRotation;
            colliderGameObject.transform.localScale = Vector3.one;

            var capsuleCollider = colliderGameObject.AddComponent<MagicaCapsuleCollider>();
            capsuleCollider.direction = fitResult.Direction;
            capsuleCollider.center = fitResult.Center;
            capsuleCollider.SetSize(fitResult.RadiusAtMin, fitResult.RadiusAtMax, fitResult.Length);
            capsuleCollider.reverseDirection = fitResult.ReverseDirection;
            capsuleCollider.UpdateParameters();

            return capsuleCollider;
        }

        private MagicaCapsuleCollider CreateDefaultColliderForBone(Transform boneTransform)
        {
            Debug.LogWarning($"Could not determine mesh shape for bone '{boneTransform.name}'. Creating a fallback collider.");

            var colliderGameObject = new GameObject($"{GeneratedColliderName} (Fallback)");
            colliderGameObject.transform.parent = boneTransform;
            colliderGameObject.transform.localPosition = Vector3.zero;
            colliderGameObject.transform.localRotation = Quaternion.identity;
            colliderGameObject.transform.localScale = Vector3.one;
            var capsuleCollider = colliderGameObject.AddComponent<MagicaCapsuleCollider>();

            if (boneTransform.childCount > 0)
            {
                float maxDistance = 0f;
                Vector3 longestChildLocal = Vector3.up * 0.05f;

                foreach (Transform child in boneTransform)
                {
                    Vector3 childLocal = child.localPosition;
                    float distance = childLocal.magnitude;

                    if (distance > maxDistance)
                    {
                        maxDistance = distance;
                        longestChildLocal = childLocal;
                    }
                }

                float radius = Mathf.Clamp(maxDistance * 0.18f, 0.01f, 0.08f);
                float length = Mathf.Max(maxDistance, radius * 2.0f);

                if (ColliderCapsuleFitter.DetectBoneFitRole(boneTransform) == BoneFitRole.UpperChest)
                {
                    radius *= 1.1f;
                }

                if (longestChildLocal.sqrMagnitude > 1.0e-8f)
                {
                    colliderGameObject.transform.localRotation = Quaternion.FromToRotation(Vector3.up, longestChildLocal.normalized);
                }

                capsuleCollider.SetSize(radius, radius, length);
                capsuleCollider.center = new Vector3(0.0f, length * 0.5f, 0.0f);
                capsuleCollider.direction = MagicaCapsuleCollider.Direction.Y;
                capsuleCollider.UpdateParameters();
                return capsuleCollider;
            }
            else
            {
                float defaultRadius = 0.02f;
                float defaultLength = 0.02f;

                if (ColliderCapsuleFitter.DetectBoneFitRole(boneTransform) == BoneFitRole.UpperChest)
                {
                    defaultRadius = 0.03f;
                    defaultLength = 0.04f;
                }

                capsuleCollider.SetSize(defaultRadius, defaultRadius, defaultLength);
                capsuleCollider.center = Vector3.zero;
                capsuleCollider.direction = MagicaCapsuleCollider.Direction.Y;
                capsuleCollider.UpdateParameters();
                return capsuleCollider;
            }
        }
    }
}
